import { createAccessControl } from "better-auth/plugins/access";
import { defaultStatements, adminAc } from "better-auth/plugins/admin/access";
import { Role } from "./generated/prisma/enums";

export const statements = {
  ...defaultStatements,
  userProfiles: ["create", "update", "delete", "view"] as const,
  attendance: ["mark", "view", "list"] as const,
  leaveRequest: [
    "create",
    "list",
    "update",
    "get",
    "list:past",
    "delete:own",
    "update:own",
    "approve",
  ] as const,
  subject: [
    "create",
    "list",
    "get",
    "update",
    "delete",
    "list:registered",
    "get:registered",
  ] as const,
  semesters: ["create", "list", "get", "update", "delete"] as const,
  subjectOfferings: ["create", "list", "get", "update", "delete"] as const,
  complaints: [
    "create",
    "list:own",
    "list",
    "get",
    "update:own",
    "update",
    "assign",
    "delete:own",
    "approve",
  ] as const,
  announcements: ["create", "list", "get", "update", "delete"] as const,
} as const;

export const access = createAccessControl(statements);

export const roles = {
  STUDENT: access.newRole({
    userProfiles: ["view"],
    user: [],
    session: [],
    attendance: ["view", "list"],
    leaveRequest: [
      "create",
      "get",
      "list",
      "list:past",
      "delete:own",
      "update:own",
    ],
    subject: ["list", "list:registered", "get:registered"],
    semesters: [],
    subjectOfferings: ["list"],
    complaints: ["list:own", "get", "create", "update:own", "delete:own"],
    announcements: ["list", "get"],
  }),

  ADMIN: access.newRole({
    ...defaultStatements,
    ...adminAc.statements,
    userProfiles: ["create", "update", "delete", "view"],
    attendance: ["view"],
    leaveRequest: ["get", "list", "update", "list:past"],
    subject: ["create", "get", "list", "update", "delete"],
    semesters: ["create", "list", "get", "update", "delete"],
    subjectOfferings: ["list", "get", "update", "delete", "create"],
    complaints: [],
    announcements: ["create", "list", "get", "update", "delete"],
  }),

  PROFESSOR: access.newRole({
    userProfiles: ["view"],
    user: ["list", "get"],
    session: [],
    attendance: ["view", "mark", "list"],
    leaveRequest: ["get", "list", "list:past", "update"],
    subject: ["list", "get"],
    semesters: ["list", "get"],
    subjectOfferings: ["list"],
    complaints: ["get", "update", "list", "assign", "approve"],
    announcements: [],
  }),
  ACCOUNTANT: access.newRole({
    userProfiles: ["view"],
    user: [],
    session: [],
    attendance: [],
    leaveRequest: [],
    subject: ["list"],
    semesters: ["list", "get"],
    subjectOfferings: ["list"],
    complaints: [],
    announcements: ["create", "list", "get", "update", "delete"],
  }),
  DIRECTOR: access.newRole({
    userProfiles: ["create", "update", "view"],
    user: ["list", "set-role", "get", "update"],
    session: [],
    attendance: ["view"],
    leaveRequest: ["get", "list", "list:past"],
    subject: ["list", "get"],
    semesters: ["list", "get"],
    subjectOfferings: ["list", "get", "update"],
    complaints: [],
    announcements: [],
  }),
  HOD: access.newRole({
    userProfiles: ["view", "update"],
    user: ["list", "get"],
    session: [],
    attendance: ["view"],
    leaveRequest: ["get", "list", "update", "list:past", "approve"],
    subject: ["list", "get", "update"],
    semesters: ["list", "get"],
    subjectOfferings: ["list", "get"],
    complaints: ["list", "assign", "get", "update", "list", "approve"],
    announcements: ["create", "list", "get", "update", "delete"],
  }),
  USER: access.newRole({
    userProfiles: ["view"],
    user: [],
    session: [],
    attendance: [],
    leaveRequest: [],
    subject: [],
    semesters: [],
    subjectOfferings: [],
    complaints: [],
    announcements: [],
  }),
  BATCH_ADVISOR: access.newRole({
    userProfiles: ["view", "update"],
    user: ["get", "update", "list"],
    session: [],
    attendance: ["list", "view", "mark"],
    leaveRequest: ["get", "list", "update", "list:past", "approve"],
    subject: ["list", "get"],
    semesters: ["list", "get"],
    subjectOfferings: ["list"],
    complaints: ["get", "update", "list", "assign", "approve"],
    announcements: [],
  }),
  CLERK: access.newRole({
    userProfiles: ["view"],
    user: [],
    session: [],
    attendance: [],
    leaveRequest: [],
    subject: [],
    semesters: [],
    subjectOfferings: [],
    complaints: [],
    announcements: [],
  }),
} satisfies Record<Role, ReturnType<typeof access.newRole>>;

export type Statements = typeof statements;

export type PermissionMap = {
  [K in keyof Statements]?: Statements[K][number][];
};
